version: '3.7'
services:
    dns-server:
      container_name: dns-server
      image: 'jpillora/dnsmasq'
      restart: always
      environment:
            - TZ=Asia/Shanghai
            - HTTP_USER=foo
            - HTTP_PASS=bar
      ports:
            - "53:53/udp"
            - "5380:8080"
      volumes:
            - "./dns/dnsmasq.conf:/etc/dmZsmasq.conf"
