version: '3'

services:
  db:
    container_name: autoams-db
    image: mysql:8
    command: --default-authentication-plugin=mysql_native_password --init-file /code/files/init.sql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_USER: dba
      MYSQL_PASSWORD: 123456
      MYSQL_DATABASE: autoams
    volumes:
      - .:/code
      - autoams_db_data_volume:/var/lib/mysql
    security_opt:
      - seccomp:unconfined
    ports:
      - "3307:3306" # same for localhost dev


volumes:
    autoams_db_data_volume:
