version: '2.2'

services:
    tor_jp: # 日本
        container_name: tor_jp
        image: rdsubhas/tor-privoxy-alpine
        volumes:
            - ./country/jp/torrc:/etc/service/tor/torrc
        restart: always
        ports:
            - "8120:8118"

    tor_us: # 美国
        container_name: tor_us
        image: rdsubhas/tor-privoxy-alpine
        volumes:
            - ./country/us/torrc:/etc/service/tor/torrc
        restart: always
        ports:
            - "8121:8118"

    tor_id: # 印尼
        container_name: tor_id
        image: rdsubhas/tor-privoxy-alpine
        volumes:
            - ./country/id/torrc:/etc/service/tor/torrc
        restart: always
        ports:
            - "8122:8118"

    tor_sg: # 新加坡
        container_name: tor_sg
        image: rdsubhas/tor-privoxy-alpine
        volumes:
            - ./country/sg/torrc:/etc/service/tor/torrc
        restart: always
        ports:
            - "8123:8118"

    tor_my: # 马来西亚
        container_name: tor_my
        image: rdsubhas/tor-privoxy-alpine
        volumes:
            - ./country/my/torrc:/etc/service/tor/torrc
        restart: always
        ports:
            - "8124:8118"

    tor_th: # 泰国
        container_name: tor_th
        image: rdsubhas/tor-privoxy-alpine
        volumes:
            - ./country/th/torrc:/etc/service/tor/torrc
        restart: always
        ports:
            - "8125:8118"

    tor_hk: # 香港
        container_name: tor_hk
        image: rdsubhas/tor-privoxy-alpine
        volumes:
            - ./country/hk/torrc:/etc/service/tor/torrc
        restart: always
        ports:
            - "8126:8118"

    tor_tw: # 台湾
        container_name: tor_tw
        image: rdsubhas/tor-privoxy-alpine
        volumes:
            - ./country/tw/torrc:/etc/service/tor/torrc
        restart: always
        ports:
            - "8127:8118"

    tor_kr: # 韩国
        container_name: tor_kr
        image: rdsubhas/tor-privoxy-alpine
        volumes:
            - ./country/kr/torrc:/etc/service/tor/torrc
        restart: always
        ports:
            - "8128:8118"

    tor_fr: # 法国
        container_name: tor_fr
        image: rdsubhas/tor-privoxy-alpine
        volumes:
            - ./country/fr/torrc:/etc/service/tor/torrc
        restart: always
        ports:
            - "8129:8118"

    tor_au: # 澳大利亚
        container_name: tor_au
        image: rdsubhas/tor-privoxy-alpine
        volumes:
            - ./country/au/torrc:/etc/service/tor/torrc
        restart: always
        ports:
            - "8130:8118"

    tor_ca: # 加拿大
        container_name: tor_ca
        image: rdsubhas/tor-privoxy-alpine
        volumes:
            - ./country/ca/torrc:/etc/service/tor/torrc
        restart: always
        ports:
            - "8131:8118"

    tor_de: # 德国
        container_name: tor_de
        image: rdsubhas/tor-privoxy-alpine
        volumes:
            - ./country/de/torrc:/etc/service/tor/torrc
        restart: always
        ports:
            - "8132:8118"

    tor_gb: # 英国
        container_name: tor_gb
        image: rdsubhas/tor-privoxy-alpine
        volumes:
            - ./country/gb/torrc:/etc/service/tor/torrc
        restart: always
        ports:
            - "8133:8118"

    tor_nz: # 新西兰
        container_name: tor_nz
        image: rdsubhas/tor-privoxy-alpine
        volumes:
            - ./country/nz/torrc:/etc/service/tor/torrc
        restart: always
        ports:
            - "8134:8118"

    tor_vn: # 越南
        container_name: tor_vn
        image: rdsubhas/tor-privoxy-alpine
        volumes:
            - ./country/vn/torrc:/etc/service/tor/torrc
        restart: always
        ports:
            - "8135:8118"

volumes:
    tor_data_volume:
