version: '3'

services:

  ssdb:
    image: evoup/ssdb
    container_name: ssdb
    #build:
      #context: .
      #dockerfile: ./Dockerfile
    # command: /ssdb/ssdb-server /ssdb/ssdb.conf
    volumes:
      - ./volumes/ssdb/data:/ssdb/var
      # - ./configs/ssdb/ssdb.conf:/ssdb/ssdb.conf:ro
    ports:
      - 8888:8888
    networks:
      - ssdb-net
    restart: always

  ssdb-admin:
    image: jhao104/ssdb-admin
    container_name: ssdb-admin
    environment:
      - DB_CONFIG=172.17.0.1:8888
    ports:
      - 5000:5000
    restart: always


networks:
  ssdb-net:
    driver: bridge
