version: '3'

services:

  ssdb0:
    image: evoup/ssdb
    container_name: ssdb0-localhost
    #build:
      #context: .
      #dockerfile: ./Dockerfile
    # command: /ssdb/ssdb-server /ssdb/ssdb.conf
    volumes:
      - ./volumes/ssdb0/data:/ssdb/var
      # - ./configs/ssdb/ssdb.conf:/ssdb/ssdb.conf:ro
    ports:
      - 8888:8888
    networks:
      - ssdb-net
    restart: always

  ssdb1:
    image: evoup/ssdb
    container_name: ssdb1-localhost
    #build:
      #context: .
      #dockerfile: ./Dockerfile
    # command: /ssdb/ssdb-server /ssdb/ssdb.conf
    volumes:
      - ./volumes/ssdb1/data:/ssdb/var
      # - ./configs/ssdb/ssdb.conf:/ssdb/ssdb.conf:ro
    ports:
      - 8889:8888
    networks:
      - ssdb-net
    restart: always

  ssdb-admin:
    image: jhao104/ssdb-admin
    container_name: ssdb-admin
    environment:
        - DB_CONFIG=ssdb0-localhost:8888,ssdb1-localhost:8889
    ports:
      - 5000:5000
    restart: always
    networks:
      - ssdb-net


networks:
  ssdb-net:
    driver: bridge
